---

- hosts: all
  become: true
  tasks:


  - name: install apache plus php packages
    package:
      update_cache: yes
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent
